services:
  - name: web
    type: web
    runtime: python
    buildCommand: bash build.sh
    startCommand: gunicorn -b 0.0.0.0 final_project.wsgi:application
    plan: free

  - name: websocket
    type: web
    runtime: python
    startCommand: daphne -b 0.0.0.0 final_project.asgi:application
    plan: free